### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by jcubic** [patmooney/node-terminal-art#5]
I've created Demo using your project you can link to it from your readme if you want.

https://codepen.io/jcubic/pen/abzNaap?editors=0010

you can type `img <url>` to render the image using your library. It use old version because your library don't work from CDN in browser (it's node.js only).

**Comment by patmooney** [comment]
Thanks @jcubic, Is it an old version because you haven't uploaded the newest to your CDN or has there been a compatibility issue introduced? I think the library running in the browser is probably a very edge case though ;) not many terminals run in the browser!
Currently working on a few things to get the processing time right down and maybe introduce animated gifs. If the library can be sped up fast enough (currently takes about ~200ms per frame on a quick-ish machine) then I'll have a look at video playback. Will need to get it down to at least 20fps though.
